-- Gui to Lua
-- Version: 3

-- Instances:
local MainRemakeSAT = Instance.new("Frame")
local F3x = Instance.new("TextButton")
local NameSAT = Instance.new("TextLabel")
local CloseSAT = Instance.new("TextButton")
local pan = Instance.new("TextButton")
local kAll = Instance.new("TextButton")
local chathax = Instance.new("TextButton")
local r6 = Instance.new("TextButton")
local bigBan = Instance.new("TextButton")
local dex = Instance.new("TextButton")

--Properties:

MainRemakeSAT.Name = "SATFucker"
MainRemakeSAT.Parent = game.Players.LocalPlayer.PlayerGui:FindFirstChild("obx")
game.Players.LocalPlayer.PlayerGui:FindFirstChild("obx"):FindFirstChild("MainRemake"):Destroy()
MainRemakeSAT.BackgroundColor3 = Color3.new(0.168627, 0.168627, 0.168627)
MainRemakeSAT.BorderColor3 = Color3.new(0.101961, 0.101961, 0.101961)
MainRemakeSAT.BorderSizePixel = 0
MainRemakeSAT.Position = UDim2.new(0.0410584211, 0, 0.265654653, 0)
MainRemakeSAT.Size = UDim2.new(0, 508, 0, 245)
MainRemakeSAT.Active = true
MainRemakeSAT.Draggable = true

F3x.Name = "F3x"
F3x.Parent = MainRemakeSAT
F3x.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
F3x.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
F3x.BorderSizePixel = 0
F3x.Position = UDim2.new(0, 364, 0, 44)
F3x.Size = UDim2.new(0, 129, 0, 33)
F3x.Font = Enum.Font.SourceSansLight
F3x.Text = "BTools"
F3x.TextColor3 = Color3.new(1, 1, 1)
F3x.TextSize = 22
F3x.TextWrapped = true

NameSAT.Name = "Name"
NameSAT.Parent = MainRemakeSAT
NameSAT.BackgroundColor3 = Color3.new(0.101961, 0.101961, 0.101961)
NameSAT.BorderColor3 = Color3.new(0.0823529, 0.0823529, 0.0823529)
NameSAT.BorderSizePixel = 0
NameSAT.Size = UDim2.new(0, 471, 0, 28)
NameSAT.Font = Enum.Font.SourceSansLight
NameSAT.Text = "OBX SAT Fucker"
NameSAT.TextColor3 = Color3.new(1, 1, 1)
NameSAT.TextSize = 25

CloseSAT.Name = "Close"
CloseSAT.Parent = NameSAT
CloseSAT.BackgroundColor3 = Color3.new(0.309804, 0, 0)
CloseSAT.BorderColor3 = Color3.new(0.0823529, 0.0823529, 0.0823529)
CloseSAT.BorderSizePixel = 0
CloseSAT.Position = UDim2.new(1.00000012, 0, 0, 0)
CloseSAT.Size = UDim2.new(0, 36, 0, 28)
CloseSAT.Font = Enum.Font.Code
CloseSAT.Text = "X"
CloseSAT.TextColor3 = Color3.new(0, 0, 0)
CloseSAT.TextSize = 25

pan.Name = "pan"
pan.Parent = MainRemakeSAT
pan.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
pan.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
pan.BorderSizePixel = 0
pan.Position = UDim2.new(0, 189, 0, 44)
pan.Size = UDim2.new(0, 129, 0, 33)
pan.Font = Enum.Font.SourceSansLight
pan.Text = "PUBG Pan"
pan.TextColor3 = Color3.new(1, 1, 1)
pan.TextSize = 22
pan.TextWrapped = true

kAll.Name = "kAll"
kAll.Parent = MainRemakeSAT
kAll.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
kAll.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
kAll.BorderSizePixel = 0
kAll.Position = UDim2.new(0, 15, 0, 44)
kAll.Size = UDim2.new(0, 129, 0, 33)
kAll.Font = Enum.Font.SourceSansLight
kAll.Text = "Kill All"
kAll.TextColor3 = Color3.new(1, 1, 1)
kAll.TextSize = 22
kAll.TextWrapped = true

chathax.Name = "chathax"
chathax.Parent = MainRemakeSAT
chathax.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
chathax.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
chathax.BorderSizePixel = 0
chathax.Position = UDim2.new(0, 15, 0, 106)
chathax.Size = UDim2.new(0, 129, 0, 33)
chathax.Font = Enum.Font.SourceSansLight
chathax.Text = "Chat Hax"
chathax.TextColor3 = Color3.new(1, 1, 1)
chathax.TextSize = 22
chathax.TextWrapped = true

r6.Name = "r6"
r6.Parent = MainRemakeSAT
r6.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
r6.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
r6.BorderSizePixel = 0
r6.Position = UDim2.new(0, 189, 0, 106)
r6.Size = UDim2.new(0, 129, 0, 33)
r6.Font = Enum.Font.SourceSansLight
r6.Text = "R6"
r6.TextColor3 = Color3.new(1, 1, 1)
r6.TextSize = 22
r6.TextWrapped = true

bigBan.Name = "bigBan"
bigBan.Parent = MainRemakeSAT
bigBan.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
bigBan.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
bigBan.BorderSizePixel = 0
bigBan.Position = UDim2.new(0, 364, 0, 106)
bigBan.Size = UDim2.new(0, 129, 0, 33)
bigBan.Font = Enum.Font.SourceSansLight
bigBan.Text = "Big Ban"
bigBan.TextColor3 = Color3.new(1, 1, 1)
bigBan.TextSize = 22
bigBan.TextWrapped = true

dex.Name = "dex"
dex.Parent = MainRemakeSAT
dex.BackgroundColor3 = Color3.new(0.0941177, 0.0941177, 0.0941177)
dex.BorderColor3 = Color3.new(0.266667, 0.266667, 0.266667)
dex.BorderSizePixel = 0
dex.Position = UDim2.new(0, 14, 0, 192)
dex.Size = UDim2.new(0, 478, 0, 33)
dex.Font = Enum.Font.SourceSansLight
dex.Text = "Dex Explorer"
dex.TextColor3 = Color3.new(1, 1, 1)
dex.TextSize = 22
dex.TextWrapped = true


CloseSAT.MouseButton1Click:Connect(function()
	MainRemakeSAT:Destroy()
end)

kAll.MouseButton1Click:Connect(function()
	-- Script generated by R2Sv2
	-- R2Sv2 developed by Luckyxero fixed by Overqualified
	local Event = game:GetService("ReplicatedStorage")["ACS_Engine"].Eventos.Damage
	for i,v in pairs(game.Players:GetPlayers()) do
    	local A_0 = v.Character
    	local A_1 = A_0.Humanoid
    	local A_2 = A_1.MaxHealth
   		local A_3 = 0
    	local A_4 = 0
   		Event:FireServer(A_1, A_2, A_3, A_4)
	end
end)

pan.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("pan")
		end
	end
end)

F3x.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("f3x")
		end
	end
end)

chathax.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("chathax")
		end
	end
end)

r6.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("r6")
		end
	end
end)

pan.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("pan")
		end
	end
end)

bigBan.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("bigban")
		end
	end
end)

dex.MouseButton1Click:Connect(function()
	for i,v in pairs(game.ReplicatedStorage:GetChildren()) do
		if v.Name == "GetDatabase" then
			v:FireServer("dex")
		end
	end
end)
